version: 2.1

executors:
  packer-image: # declares a reusable executor
    working_directory: ~/ami # directory where steps will run
    docker:
      - image: circleci/python:2.7-jessie # the primary container, where your job's commands are run

commands:
  install_packages:
    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install curl unzip -y
            curl https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip
            unzip packer*.zip
            chmod +x packer

  build_packer:
    steps:
      - run:
          name: Build Packer
          command: packer build ./ami.json

  validate_packer:
    steps:
      - run: #Validate packer
          name: Validate base
          command: packer validate ./ami.json

  install_awscli:
    steps:
      - run:
          name: Install awscli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

jobs:
  build:
    executor: packer-image
    steps:
      - install_packages
      - install_awscli
      - validate_packer
      - build-packer

workflows:
  build_deploy:
    jobs:
      - build
          # filters:
          #   branches:
          #     only:
          #       - master
