version: 2.1

executors:
  packer-image: # declares a reusable executor
    working_directory: ~/ami # directory where steps will run
    docker:
      - image: hashicorp/packer:1.1.1 # the primary container, where your job's commands are run

commands:
  build-packer:
    steps:
      - run:
          name: Build Packer
          command: packer build ./ami.json

  validate_packer:
    steps:
      - run: #Validate packer
          name: Validate base
          command: packer validate ./ami.json

  install_awscli:
    steps:
      - run:
          name: Install awscli
          command: |
            sudo apt update 
            sudo apt install curl -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

jobs:
  build:
    executor: packer-image
    steps:
      - install_awscli
      - validate_packer
      - build-packer

workflows:
  build_deploy:
    jobs:
      - build
          # filters:
          #   branches:
          #     only:
          #       - master
