version: 2.1

executors:
  packer-image: # declares a reusable executor
    working_directory: ~/ami # directory where steps will run
    docker:
      - image: hashicorp/packer:1.1.1 # the primary container, where your job's commands are run

commands:
  build_packer:
    steps:
      - run:
          name: Build Packer
          command: packer build ./ami.json

  validate_packer:
    steps:
      - run: #Validate packer
          name: Validate base
          command: packer validate ./ami.json

  install_awscli:
    steps:
      - run:
          name: Install awscli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

jobs:
  build:
    executor: packer-image
    steps:
      - checkout: # check out the code in the project directory
          path: ~/ami
      - install_awscli
      - validate_packer
      - build_packer

workflows:
  build_deploy:
    jobs:
      - build
          # filters:
          #   branches:
          #     only:
          #       - master
